version: '3'

services:
  postgres_db:
    image: postgres:14.5
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5430:5432'
    volumes:
      - /home/docker-storage/postgresql:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4:latest
    container_name: postgres_admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5480:80'
    volumes:
      - /home/docker-storage/pgadmin:/var/lib/pgadmin
